version: "3.4"
services:
  backend:
    build:
      context: camel-backend
      target: development
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./camel-backend:/usr/src/app/server
      - backend-node-modules:/usr/src/app/server/node_modules
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://db:27017/camel
    stdin_open: true
    tty: true
  frontend:
    build:
      context: camel-frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./camel-frontend:/usr/src/app/client
      - frontend-node-modules:/usr/src/app/client/node_modules
    environment:
      NODE_ENV: development
      API_URL: http://localhost:8000
    stdin_open: true
    tty: true
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
  frontend-node-modules:
  backend-node-modules:
