version: "3.4"
services:
  backend:
    build:
      context: camel-backend
      target: development
    depends_on:
      - db  
    ports: 
      8000:8000
    volumes:
      - .:/usr/src/app/server
    stdin_open: true
    tty: true
  frontend:
    build:
      context: camel-front
      target: development
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app/client 
    environment:
      NODE_ENV: development
      API_URL: localhost:8000
    stdin_open: true
    tty: true
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:    